package initialize

import (
	"bctbackend/algorithms"
	"bctbackend/commands/common"
	"bctbackend/database"
	dberr "bctbackend/database/errors"
	"bctbackend/database/models"
	"bctbackend/database/queries"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"

	"github.com/MakeNowJust/heredoc"
	"github.com/spf13/cobra"
)

type InitializeCommand struct {
	common.Command
}

func NewInitializeCommand() *cobra.Command {
	command := cobra.Command{
		Use:   "init",
		Short: "Initialize backend components",
		Long: heredoc.Doc(`
							Commands to initialize different parts of the back-end.
					   `),
	}

	command.AddCommand(NewInitializeHtmlCommand())
	command.AddCommand(NewInitializeAllCommand())

	return &command
}

func (c *InitializeCommand) generateConfigurationFile() error {
	fileExists, err := algorithms.FileExists("bctconfig.yaml")
	if err != nil {
		c.PrintErrorf("Failed to check if configuration file exists: %v\n", err)
		return err
	}
	if fileExists {
		c.Printf("Configuration file already exists; I will not overwrite it\n")
		return nil
	}

	contents := heredoc.Doc(`
		database: "bct.db"
		labelGeneration:
		  barcode:
		    width: 150
		    height: 25
		server:
		  port: 8000
		  html: index.html
		  pruneExpiredSessionsInterval: 3600
		  cookieDomain: "bct-sales.myaddr.io"
		  debug: false
		  swagger: false
		log:
		  file: "bct.log"
		  maxSizeMegabytes: 10
		  maxBackups: 3
		  maxAgeDays: 28
		  compression: false
		email:
 		  sender:
		    token: "TODO Application password generated by Google"
		    address: "bctsales.backend@gmail.com"
		  receiver:
		    address: "TODO Email address of receiver"
	`)

	if err := os.WriteFile("bctconfig.yaml", []byte(contents), 0644); err != nil {
		c.PrintErrorf("Failed to create configuration file: %v\n", err)
		return err
	}

	c.Printf("Configuration file created successfully\n")
	return nil
}

func (c *InitializeCommand) downloadHTMLFile(overwrite bool) (err error) {
	filename := "index.html"

	if !overwrite {
		fileExists, err := algorithms.FileExists(filename)
		if err != nil {
			c.PrintErrorf("Failed to check if %s exists: %v\n", filename, err)
			return err
		}
		if fileExists {
			c.Printf("File %s already exists; I will not overwrite it\n", filename)
			return nil
		}
	}

	out, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer func() {
		if errClose := out.Close(); errClose != nil {
			c.PrintErrorf("Failed to close file %s\n", filename)
			err = errors.Join(err, errClose)
		}
	}()

	url := "https://github.com/bct-sales/go-frontend/releases/latest/download/index.html"
	resp, err := http.Get(url)
	if err != nil {
		return err
	}
	defer func() {
		if errClose := resp.Body.Close(); errClose != nil {
			c.PrintErrorf("Failed to close response body\n")
			err = errors.Join(err, errClose)
		}
	}()

	if resp.StatusCode != http.StatusOK {
		c.PrintErrorf("Failed to download file from %s: %s\n", url, resp.Status)
		return fmt.Errorf("bad status: %s", resp.Status)
	}

	if _, err := io.Copy(out, resp.Body); err != nil {
		return err
	}

	c.Printf("HTML file downloaded successfully to %s\n", filename)

	return nil
}

func (c *InitializeCommand) createDatabaseFile() (r_err error) {
	databasePath := "bct.db"
	db, err := database.CreateDatabase(databasePath)

	if err != nil {
		if errors.Is(err, dberr.ErrDatabaseAlreadyExists) {
			c.Printf("Database file %s already exists; I will not overwrite it.\n", databasePath)
			return nil
		}

		c.PrintErrorf("Failed to create database file: %v\n", err)
		return err
	}

	defer func() {
		if err := db.Close(); err != nil {
			c.PrintErrorf("Failed to close database %s\n", databasePath)
			r_err = errors.Join(r_err, err)
		}
	}()

	c.Printf("Database file successfully created at %s\n", databasePath)

	if err := database.InitializeDatabase(db); err != nil {
		c.PrintErrorf("Failed to initialize database: %v\n", err)
		return err
	}

	{
		err := common.GenerateDefaultCategories(func(id models.ID, name string) error {
			return queries.AddCategoryWithID(db, id, name)
		})

		if err != nil {
			c.PrintErrorf("Failed to add default categories: %v\n", err)
			return err
		}
	}

	c.Printf("Database initialized successfully\n")

	return nil
}
