openapi: 3.0.4
info:
  title: BCT Sales REST API
  description: |-
    BCT Sales REST API
  termsOfService: https://swagger.io/terms/
  contact:
    email: frederic.vogels+bctsales@gmail.com
  version: 1.10.3
externalDocs:
  description: Find out more about BCT Sales Backend
  url: https://github.com/bct-sales/go-backend
tags:
  - name: user
    description: User related functionality
  - name: item
    description: Item related functionality
  - name: sale
    description: Sale related functionality
  - name: category
    description: Category related functionality
  - name: admin
    description: Admin-accessible functionality
  - name: seller
    description: Seller-accessible functionality
  - name: cashier
    description: Cashier-accessible functionality
  - name: authentication
    description: Authentication related functionality
paths:
  /api/v1/users:
    get:
      tags:
        - user
        - admin
      summary: List all users
      description: >
        Returns a list of all users.
        This operation is reserved for admins.
      operationId: ListUsers
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int64
                          example: 10
                        password:
                          type: string
                          example: azer1234
                        role:
                          type: string
                          enum:
                            - admin
                            - seller
                            - cashier
                          example: seller
                        createdAt:
                          $ref: '#/components/schemas/DateTime'
                        lastActivity:
                          $ref: '#/components/schemas/DateTime'
        '400':
          description: Failed to parse request body
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
        '403':
          description: >
            Forbidden operation for the current user.
            Only admins are allowed to perform this operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
  /api/v1/sales:
    post:
      tags:
        - authentication
      summary: Registers a sale
      description: >
        Registers a sale.
        Reserved for cashiers.
      operationId: AddSale
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                itemIds:
                  type: array
                  items:
                    type: integer
                    format: int64
                    description: item identifier
                  example:
                    [1, 4, 100]
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  saleId:
                    type: integer
                    format: uint64
                    description: Id of the newly added sale
                    example: 5
        '400':
          description: Failed to parse request body
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
        '403':
          description: >
            Forbidden operation for the current user.
            Only admins are allowed to perform this operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
        '404':
          description: >
            The provided list of item ids contains an invalid item id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
  /api/v1/seller/{sellerId}/items:
    post:
      tags:
        - item
        - seller
      summary: Add seller item
      parameters:
        - in: path
          name: sellerId
          schema:
            type: integer
            format: uint64
          required: true
          description: Id of item owner
      description: >
        Adds an item to the database.
        Reserved for sellers.
      operationId: AddSellerItem
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                price:
                  type: integer
                  description: Price in cents
                  example: 150
                description:
                  type: string
                  description: Description of the item
                  example: "Nike sneakers"
                categoryId:
                  type: integer
                  format: uint64
                  description: Id of the item category
                  example: 1
                donation:
                  type: boolean
                  description: Whether proceeds will be donated to the BCT
                  example: false
                charity:
                  type: boolean
                  description: Whether the item will be donated to charity if unsold
                  example: false
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  itemId:
                    type: integer
                    format: uint64
                    example: 158
        '400':
          description: Failed to parse request body
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
        '403':
          description: >
            Forbidden operation for the current user.
            Only admins are allowed to perform this operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
        '404':
          description: >
            The provided list of item ids contains an invalid item id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
  /api/v1/items:
    get:
      tags:
        - item
        - admin
        - cashier
      summary: List items
      description: >
        Returns a list of items.
        This operation is reserved for admins and cashiers.
      operationId: ListUsers
      parameters:
        - in: query
          name: items
          description: >
            Determines which items to show based on visibility.

            - **all**: show all items

            - **hidden**: show only invisible items

            - **visible**: show only visible items

            - if omitted: same as **visible**
          schema:
            type: string
            enum:
              - all
              - hidden
              - visible
          required: false
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            example: 100
          description: Maximum number of items to return
          required: false
        - in: query
          name: offset
          description: >
            Index of item to start listing at.
          schema:
            type: integer
            minimum: 0
            example: 1500
          required: false
        - in: query
          name: category
          description: Filter items based on category
          schema:
            type: integer
            format: uint64
            example: 2
          required: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalItemCount:
                    type: integer
                    description: >
                      Total number of items
                    example:
                      53
                  totalItemValue:
                    type: integer
                    example: 15250
                    description: >
                      Total value of items in cents
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        itemId:
                          type: integer
                          format: int64
                          example: 10
                        addedAt:
                          $ref: '#/components/schemas/DateTime'
                        description:
                          type: string
                        priceInCents:
                          type: integer
                        categoryId:
                          type: integer
                          format: uint64
                        sellerId:
                          type: integer
                          format: uint64
                        donation:
                          type: boolean
                        charity:
                          type: boolean
                        frozen:
                          type: boolean
        '400':
          description: Failed to parse request body or query parameters
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
        '403':
          description: >
            Forbidden operation for the current user.
            Only admins and cashiers are allowed to perform this operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
  /api/v1/login:
    post:
      tags:
        - authentication
      summary: Log in
      description: >
        Authenticates a user
      operationId: Login
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Id of the user to log in
                  example: 5
                password:
                  type: string
                  description: Password used to authenticate user
                  example: azer1234
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  role:
                    type: string
                    enum:
                      - admin
                      - seller
                      - cashier
                    description: Role of the authenticated user
                    example: seller
        '400':
          description: Failed to parse request body
        '401':
          description: Failed to authenticate user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
        '404':
          description: Unknown user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailureResponse'
components:
  schemas:
    DateTime:
      properties:
        year:
          type: integer
          example: 2025
        month:
          type: integer
          example: 10
        day:
          type: integer
          example: 5
        hour:
          type: integer
          example: 15
        minute:
          type: integer
          example: 49
        second:
          type: integer
          example: 33
        timestamp:
          type: integer
          format: int64
          example: 515468
    FailureResponse:
      properties:
        type:
          type: string
          enum:
            - unknown
            - invalid_request
            - invalid_uri_parameters
            - invalid_user_id
            - invalid_item_id
            - invalid_sale_id
            - no_such_item
            - no_such_user
            - no_such_sale
            - wrong_user
            - no_such_category
            - wrong_password
            - item_frozen
            - invalid_price
            - wrong_role
            - duplicate_item_in_sale
            - wrong_seller
            - invalid_item_description
            - missing_session_id
            - no_such_session
            - missing_items
            - invalid_layout
        details:
          type: string