name: Go Build

on:
  push:
    branches: ["release"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: release

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.1

    - name: Build
      run: cd bctbackend && go build -v ./...

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
        distribution: goreleaser
        # 'latest', 'nightly', or a semver
        version: "~> v2"
        workdir: bctbackend
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}