package rest

import (
	"bctbackend/algorithms"
	dberr "bctbackend/database/errors"
	"bctbackend/database/models"
	"bctbackend/database/queries"
	"bctbackend/pdf"
	"bctbackend/server/failure_response"
	"errors"
	"fmt"
	"net/http"

	"log/slog"
)

type Insets struct {
	Top    float64 `json:"top"`
	Bottom float64 `json:"bottom"`
	Left   float64 `json:"left"`
	Right  float64 `json:"right"`
}

type Layout struct {
	PaperWidth   float64 `json:"paperWidth"`
	PaperHeight  float64 `json:"paperHeight"`
	PaperMargins Insets  `json:"paperMargins"`
	Columns      int     `json:"columns"`
	Rows         int     `json:"rows"`
	LabelMargins Insets  `json:"labelMargins"`
	LabelPadding Insets  `json:"labelPadding"`
	FontSize     float64 `json:"fontSize"`
}

type GenerateLabelsPayload struct {
	Layout  Layout      `json:"layout"`
	ItemIds []models.Id `json:"itemIds"`
}

type generateLabelsEndpoint struct {
	HandlerFunctionArguments
}

func GenerateLabels(arguments *HandlerFunctionArguments) {
	endpoint := &generateLabelsEndpoint{
		HandlerFunctionArguments: *arguments,
	}

	endpoint.execute()
}

func (ep *generateLabelsEndpoint) execute() {
	if !ep.RoleId.IsSeller() {
		ep.Logger.InvalidRequest("Blocked attempt at generating labels by a user with the wrong role")
		failure_response.WrongRole(ep.Context, "Only sellers can generate labels")
		return
	}

	var payload GenerateLabelsPayload
	if err := ep.Context.ShouldBindJSON(&payload); err != nil {
		ep.Logger.InvalidInput("Failed to parse payload for GenerateLabels endpoint", "error", err)
		failure_response.InvalidRequest(ep.Context, "Failed to parse payload:"+err.Error())
		return
	}

	if len(payload.ItemIds) == 0 {
		ep.Logger.InvalidRequest("Blocked attempt at generating labels for zero items", "userId", ep.UserId)
		failure_response.MissingItems(ep.Context, "No items provided")
		return
	}

	itemTable, err := queries.GetItemsWithIds(ep.Database, payload.ItemIds)
	if err != nil {
		if errors.Is(err, dberr.ErrNoSuchItem) {
			ep.Logger.InvalidRequest("Blocked attempt at generating labels for non-existing items", "itemIds", payload.ItemIds, "userId", ep.UserId)
			failure_response.UnknownItem(ep.Context, err.Error())
			return
		}

		failure_response.Unknown(ep.Context, "Failed to fetch items: "+err.Error())
	}

	// Verify that all items belong to the active seller
	for _, item := range itemTable {
		if item.SellerID != ep.UserId {
			ep.Logger.InvalidRequest("Blocked attempt at generating labels for items not owned by the seller", "loggedInUserId", ep.UserId, "itemUserId", item.SellerID, "itemId", item.ItemID)
			failure_response.WrongSeller(ep.Context, "labels can only be generated by the owning seller")
			return
		}
	}

	labelData, err := ep.collectLabelData(ep.Database, itemTable, payload.ItemIds)
	if err != nil {
		ep.Logger.InternalError("Failed to collect label data", "error", err)
		failure_response.Unknown(ep.Context, "Failed to collect label data: "+err.Error())
		return
	}

	settings, err := pdf.NewLayoutSettings(
		pdf.WithPaperSize(
			payload.Layout.PaperWidth,
			payload.Layout.PaperHeight,
		),
		pdf.WithPaperMargins(
			payload.Layout.PaperMargins.Top,
			payload.Layout.PaperMargins.Right,
			payload.Layout.PaperMargins.Bottom,
			payload.Layout.PaperMargins.Left,
		),
		pdf.WithGridSize(payload.Layout.Columns, payload.Layout.Rows),
		pdf.WithLabelMargins(
			payload.Layout.LabelMargins.Top,
			payload.Layout.LabelMargins.Right,
			payload.Layout.LabelMargins.Bottom,
			payload.Layout.LabelMargins.Left,
		),
		pdf.WithLabelPadding(
			payload.Layout.LabelPadding.Top,
			payload.Layout.LabelPadding.Right,
			payload.Layout.LabelPadding.Bottom,
			payload.Layout.LabelPadding.Left,
		),
		pdf.WithFontSize(payload.Layout.FontSize),
	)
	if err != nil {
		ep.Logger.InvalidRequest("Invalid layout for label generation", "error", err)
		failure_response.InvalidLayout(ep.Context, "Invalid label layout: "+err.Error())
		return
	}

	pdfConfiguration := pdf.Configuration{
		FontDirectory: ep.Configuration.LabelGeneration.Font.Directory,
		FontFilename:  ep.Configuration.LabelGeneration.Font.Filename,
		FontFamily:    ep.Configuration.LabelGeneration.Font.Family,
		BarcodeWidth:  ep.Configuration.LabelGeneration.BarcodeWidth,
		BarcodeHeight: ep.Configuration.LabelGeneration.BarcodeHeight,
	}
	builder, err := pdf.GeneratePdf(&pdfConfiguration, settings, labelData)
	if err != nil {
		slog.Error("Failed to generate PDF", "error", err)
		failure_response.InvalidRequest(ep.Context, "Failed to generate PDF: "+err.Error())
		return
	}

	buffer, err := builder.WriteToBuffer()
	if err != nil {
		ep.Logger.InternalError("Failed to write PDF to buffer", "error", err)
		failure_response.InvalidRequest(ep.Context, "Failed to write PDF to buffer: "+err.Error())
		return
	}

	// Do this last, to ensure items are only frozen if the PDF was generated successfully
	if err := ep.freezeItems(ep.Database, payload.ItemIds); err != nil {
		ep.Logger.InternalError("Failed to freeze items", "error", err)
		failure_response.Unknown(ep.Context, "Failed to freeze items: "+err.Error())
		return
	}

	ep.Context.Header("Content-Disposition", "attachment; filename=labels.pdf")
	ep.Context.DataFromReader(
		http.StatusOK,
		int64(buffer.Len()),
		"application/pdf",
		buffer,
		map[string]string{"Content-Disposition": "attachment; filename=labels.pdf"},
	)
}

func (ep *generateLabelsEndpoint) freezeItems(db Database, itemIds []models.Id) error {
	transaction, err := db.StartTransaction()
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer transaction.Rollback()

	if err := queries.UpdateFreezeStatusOfItems(transaction, itemIds, true); err != nil {
		return fmt.Errorf("failed to freeze items: %w", err)
	}

	if err := transaction.Commit(); err != nil {
		return fmt.Errorf("failed to commit transaction: %w", err)
	}

	return nil
}

func (ep *generateLabelsEndpoint) collectLabelData(db Database, itemTable map[models.Id]*models.Item, itemIds []models.Id) ([]*pdf.LabelData, error) {
	createLabelData := func(itemId models.Id) (*pdf.LabelData, error) {
		item, ok := itemTable[itemId]
		if !ok {
			return nil, fmt.Errorf("bug: item with id %d not found; should never occur: this error should have be caught earlier", itemId)
		}

		categoryNameTable, err := queries.GetCategoryNameTable(db)
		if err != nil {
			return nil, err
		}

		return ep.createLabelDataFromItem(categoryNameTable, item)
	}

	labelData, err := algorithms.MapError(itemIds, createLabelData)
	if err != nil {
		return nil, err
	}

	return labelData, nil
}

func (ep *generateLabelsEndpoint) createLabelDataFromItem(categoryNameTable map[models.Id]string, item *models.Item) (*pdf.LabelData, error) {
	barcode := fmt.Sprintf("%dx", item.ItemID)

	category, ok := categoryNameTable[item.CategoryID]
	if !ok {
		return nil, fmt.Errorf("unknown category id: %v", item.CategoryID)
	}

	labelData := &pdf.LabelData{
		BarcodeData:      barcode,
		Description:      item.Description,
		Category:         category,
		ItemIdentifier:   int(item.ItemID),
		PriceInCents:     int(item.PriceInCents),
		SellerIdentifier: int(item.SellerID),
		Charity:          item.Charity,
		Donation:         item.Donation,
	}

	return labelData, nil
}
